name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      
      - name: Download BuildTools.jar
        run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      
      - name: Download Spigot versions
        run: |
          if [ ! -d "$HOME/.m2/repository/org/spigotmc/spigot" ]; then
            echo "Downloading Spigot versions..."
            java -jar BuildTools.jar --rev 1.8
            java -jar BuildTools.jar --rev 1.8.3
            java -jar BuildTools.jar --rev 1.8.8
            java -jar BuildTools.jar --rev 1.9
            java -jar BuildTools.jar --rev 1.9.4
            java -jar BuildTools.jar --rev 1.10.2
            java -jar BuildTools.jar --rev 1.11.2
            java -jar BuildTools.jar --rev 1.12.2
            java -jar BuildTools.jar --rev 1.13
            java -jar BuildTools.jar --rev 1.13.2
            java -jar BuildTools.jar --rev 1.14.4
            java -jar BuildTools.jar --rev 1.15.2
            java -jar BuildTools.jar --rev 1.16.1
            echo "Spigot versions downloaded."
          else
            echo "Spigot versions already downloaded."
          fi
      
      - name: Build with Maven
        run: mvn clean install